export type {
  UserAvatar,
  IUserFields,
  LeanUser,
  PublicUser,
  SearchUserResult,
  CreateUserInput,
  UserAuthRecord,
  UserSearchRecord,
  UserNameAvatar,
  UpdateUserPatch,
  AuthResult,
  DayCount,
} from './user.js';
export type {
  AdminTokenPayload,
  AdminStats,
  AdminUserListItem,
  AdminLoginResult,
} from './admin.js';
export type {
  LastMessageType,
  ChatLastMessage,
  ChatAvatar,
  IChatFields,
  PopulatedMember,
  MyChatPageLean,
  InboxLastMessageLean,
  ChatDetailsPopulated,
  PopulatedCreator,
  AdminGroupListLean,
  ListGroupsForAdminPageInput,
  ChatListItem,
  ChatListLastMessage,
  JoinedChat,
  UserChatWithLastMessage,
  IChatReadFields,
  ChatReadRecord,
  UpsertChatReadInput,
  MarkChatReadResult,
  MarkAllChatsReadResult,
  ChatUnreadCount,
  FindChatItem,
  ChatNotificationInput,
  RealtimeNotify,
  RealtimeNotificationsResult,
  ChatMutationMessageResult,
  CreateGroupChatInput,
  ChatMutationResult,
  PaginatedChatsResult,
  CreateGroupChatServiceInput,
  UpdateGroupDetailsServiceInput,
  AddGroupMembersInput,
  RemoveGroupMemberInput,
  SetGroupMemberAdminInput,
  LeaveGroupInput,
  DeleteGroupInput,
  GetMyChatsInput,
  FindChatsInput,
  GetChatDetailsInput,
  MarkChatReadInput,
  MarkAllChatsReadInput,
  GetChatMediaInput,
  CreateChatInput,
  ChatLean,
  ChatMembersOnly,
  DirectChatMembers,
  FriendChatPopulated,
  ChatWithMembersPopulated,
  UpdateChatPatch,
  UpdateGroupDetailsInput,
  ChatSharedLink,
  ChatSharedContent,
} from './chat.js';
export type {
  MessageAttachment,
  MessageReplyTo,
  MessageReplyToClient,
  MessageSenderClient,
  MessageForClient,
  MessagePopulatedSender,
  SentMessagePayload,
  SendMessageResult,
  EditMessageResult,
  DeleteMessagesResult,
  GetMessagesResult,
  GetMessageContextResult,
  SearchMessagesOptions,
  SearchMessageHit,
  SearchMessagesResult,
  JumpToDateResult,
  ListActiveDatesResult,
  MessageReceiptUser,
  FindReceiptsResult,
  PersistTextMessageInput,
  PersistTextMessageResult,
  SendAttachmentsInput,
  SendGifInput,
  GetMessagesInput,
  GetMessageContextInput,
  SearchMessagesInput,
  JumpToDateInput,
  ListActiveDatesInput,
  EditMessageInput,
  DeleteMessageInput,
  DeleteManyMessagesInput,
  ClearChatMessagesInput,
  ForwardMessagesInput,
  IMessageFields,
  UploadableFile,
  MessageListItem,
  CreateMessageInput,
  MessageRecord,
  UpdateMessagePatch,
  ToggleMessageReactionInput,
} from './message.js';
export type {
  IRequestFields,
  FriendSummary,
  NotificationItem,
  RequestLean,
  RequestWithParties,
  RequestWithSender,
  HandleFriendRequestResult,
  HandleFriendRequestInput,
  SendFriendRequestInput,
  GetMyFriendsInput,
} from './friend-request.js';
export type { LinkPreviewData } from './linkPreview.js';
// `normalizeVibeTag` is a runtime value, so it needs a value re-export — the
// `types/` barrel is the one place shared domain exports live.
export { normalizeVibeTag } from './match.js';
export type { AnonSocket, SocketRateLimiter } from './anonSocket.js';
export type {
  // Vibe
  Gender,
  VibeTag,
  // Redis session state
  SessionStatus,
  AnonSession,
  CreateSessionInput,
  MatchIdentity,
  // Reveal flow
  ConnectTokenPayload,
  VerifiedConnectToken,
  // Mongo document shapes
  IConnectionFields,
  IReportFields,
  ReportReason,
  // Queue / pairing
  WaitingCard,
  MatchCandidate,
  MatchAttempt,
  PairResult,
  IdentityCardInput,
  IdentityCardResult,
  WhisperQuota,
  // Messaging
  StoredAnonMessage,
  BufferedAnonMessage,
  AnonMessageSide,
  AcceptMessageResult,
  AnonFailureCode,
  AnonMessageAck,
  SocketAck,
  AnonLikeAck,
  AnonLikeFailureCode,
  LikeSocketAck,
  // Vibe reactions
  AnonReaction,
  AnonReactionAction,
  AnonReactionAck,
  AnonReactionEvent,
  AnonMessageReactions,
  AnonMessageReactionsBySide,
  AnonSessionReactions,
  ReactionSocketAck,
  // Likes
  LikeResult,
  SessionMessageCounts,
  // Vibe eligibility
  VibeGateInput,
  // Moderation
  ModerationReason,
  MessageVerdict,
  // Connection origin story
  ConnectionOrigin,
} from './match.js';
export type {
  PendingConnectionSideDoc,
  PendingConnectionStatusDoc,
  IPendingConnectionDocFields,
  IPendingConnection,
  ConnectionLean,
  CreateConnectionInput,
  CompleteConnectionResult,
  ConnectionAnnouncement,
  CompleteConnectionOutcome,
} from './connection.js';
export type {
  SubmitReportInput,
  CreateReportInput,
  ReportQueuePage,
  ReportLean,
} from './report.js';
export type {
  AdminLoginInput,
  AdminIdParam,
  AdminRemoveMemberParam,
  AdminActivityEventsQuery,
  AdminUsersQuery,
  AdminGroupsQuery,
  AdminMessagesQuery,
  AdminAttachmentsQuery,
  AdminImpersonationLogsQuery,
  AdminDeleteAttachmentsBody,
  AdminReportsQuery,
  AdminReportReviewBody,
} from './adminInput.js';
export type {
  GoogleSignInInput,
  SignUpStartInput,
  SignUpVerifyInput,
  SignUpResendInput,
  SignUpUpdateUsernameInput,
  SignUpCompleteInput,
  SignInInput,
  ForgotPasswordInput,
  ResetPasswordInput,
  UsernameCheckQuery,
  GetChatDetailsQuery,
  PageQuery,
  LinkPreviewQuery,
  JoinQueueBody,
  SubmitReportBody,
  CompleteConnectionBody,
  GetMessagesQuery,
  SearchMessagesQuery,
  JumpToDateQuery,
  ListActiveDatesQuery,
  SearchUserQuery,
  GetMyFriendsQuery,
  UpdateProfileInput,
  SocketNewMessagePayload,
  SocketTypingPayload,
  SocketReactionPayload,
  SignUploadBody,
  CommitAttachmentsBody,
} from './input.js';
