export const SOCKET_EVENTS = {
  NEW_MESSAGE: 'NEW_MESSAGE',
  NEW_MESSAGE_ALERT: 'NEW_MESSAGE_ALERT',
  ALERT: 'ALERT',
  REFETCH_CHATS: 'REFETCH_CHATS',
  NEW_ATTACHMENT: 'NEW_ATTACHMENT',
  NEW_REQUEST: 'NEW_REQUEST',
  START_TYPING: 'START_TYPING',
  STOP_TYPING: 'STOP_TYPING',
  CHAT_READ: 'CHAT_READ',
  MESSAGE_UPDATED: 'MESSAGE_UPDATED',
  MESSAGES_DELETED: 'MESSAGES_DELETED',
  CHAT_CLEARED: 'CHAT_CLEARED',
  MARK_CHAT_READ: 'MARK_CHAT_READ',
  ONLINE_USERS: 'ONLINE_USERS',
  USER_ONLINE: 'USER_ONLINE',
  USER_OFFLINE: 'USER_OFFLINE',
} as const

export type SocketEventName = typeof SOCKET_EVENTS[keyof typeof SOCKET_EVENTS]
